name: simpled

# Controles when the workflow will run 
on:
  # push:
  #   branches: [ main ]
  # pull_request: 
  #   branches: [ main ]
  # issues:
  #   types:
  #     - opened
  workflow_dispatch:
jobs:
  build:
    runs-on: 
      - self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: run a one-line script
        run: |
          echo Hello, World
          sleep 15
          echo Good bye

      - name: run multi-line script
        run: |
          echo "${{github.workspace}}"